ALTER TABLE course ADD COLUMN hw_count INT NOT NULL DEFAULT 10;
ALTER TABLE course ADD COLUMN prac_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE course ADD COLUMN prac_count INT NOT NULL DEFAULT 0;
